### ISSUE TITLE
Non-related resources in Cost Allocation while aggregating by custom label 

### ISSUE THREAD

**Issue by atyiadam** [opencost/opencost#1329]
Our organization is trying to introduce a new labelling scheme for better cost visibility in Kubernetes. We installed Kubecost via Helm. Using v1.95.0.

Our experience is that when we are using `namespace` for aggregation in the Cost Allocation page, the breakdown of a namespace contains the correct resources under the Controllers and Performance Insights section. However, as soon as we are trying to aggregate by a custom label eg. MWBilling_Team and select one of the aggregated values, Controllers and Performance Insights start to contain a huge number of completely unrelated resources. 

**Steps to reproduce:**
1. On the UI > Cost Allocation > Aggregated by `namespace` > `adam-test-kubecost`
    - Here both the Controller and Performance Insights panels contain the correct/expected resources

![panels_with_expected_content](https://user-images.githubusercontent.com/39131005/179990210-a801e088-9fae-401a-8679-d3ec1f697a5a.png)

2.  Create a few deployments and label them with a custom label like `MWBilling_Team: bravo`

3. On the UI > Cost Allocation > Aggregated by `MWBilling_Team` > `MWBilling_Team=bravo`
    - Here both of the aforementioned panels contain way more and completely unrelated resources as well

![panels_with_unrelated_resources](https://user-images.githubusercontent.com/39131005/179991694-591e0da5-308d-4f1d-8c18-bbcd3dcae32d.png)

In the picture above, in the Controller and Performance Insights panels a ton of unrelated resources are listed. Resources that are actually labelled with `MWBilling_Team=bravo` are shown below.

```yaml
kubectl get all -l MWBilling_Team=bravo -A
NAMESPACE            NAME                                           READY   STATUS    RESTARTS   AGE
adam-test-kubecost   pod/REDACTED-bravo-7b9ccc48c4-ggk98   1/1     Running   0          3h15m
adam-test-kubecost   pod/REDACTED-bravo-84f45777cb-wpjsw   1/1     Running   0          3h10m

NAMESPACE            NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
adam-test-kubecost   deployment.apps/REDACTED-bravo   1/1     1            1           3h30m
adam-test-kubecost   deployment.apps/REDACTED-bravo   1/1     1            1           3h30m

NAMESPACE            NAME                                                 DESIRED   CURRENT   READY   AGE
adam-test-kubecost   replicaset.apps/REDACTED-bravo-7b9ccc48c4   1         1         1       3h30m
adam-test-kubecost   replicaset.apps/REDACTED-bravo-84f45777cb   1         1         1       3h30m
```

**Comment by dwbrown2** [comment]
Really appreciate this detailed report @atyiadam! Looks like it should be able to repro fairly easily but I haven't been able to yet. cc @teevans who will likely know more here

**Comment by teevans** [comment]
Hey @atyiadam thanks for the report!! We'll dive into this and see what we figure out!

**Comment by Adam-Stack-PM** [comment]
@teevans, Working on release notes. Confirming 926 was merged into Opencost and closes this out?

**Comment by Sean-Holcomb** [comment]
This Issue was addressed in v1.96 with https://github.com/kubecost/cost-analyzer-frontend/pull/960

**Comment by atyiadam** [comment]
Hello everyone,
First of all thanks for looking into this. @Sean-Holcomb we've upgraded to v1.96 and tried aggregating by custom label again, but unfortunately we experienced the same behaviour as described in the issue (details page for a custom label still shows irrelevant resources under the `Controllers` and `Performance Insights` panel).

**Comment by jessegoodier** [comment]
Additional detail:

1. Bug: When aggregating by `label:app` the table does not allow drilldown.
2. Good: If you select `product` you can drill down.
3. Bug: When aggregating by `label:app` and then filter by a label `app:cost-analyzer` the /detail link brings up a page where 
controllers are not filtered.
4. Good: When aggregating by `label:app` and then filter by a namespace `kubecost` the /detail link is has accurate results
5. Bad: When aggregating by `Product` and then filter by label `app:cost-analzyer` the /detail link brings up a blank page
6. Good: When aggregating by `Product` and then filter by a namespace `kubecost` the /detail link is has accurate results

![image](https://user-images.githubusercontent.com/31039225/186526611-94a06e3a-3751-43dd-9554-cb09fc11782f.png)

**Comment by michaelmdresser** [comment]
To elaborate a bit:

- We are seeing an Inspect (`/details`) page issue that has been very helpfully described by @atyiadam. 
- Jesse's 1. and 2. points are a (possibly related) issue with Allocation (`/allocations`) row drilldown, which works for label alias (e.g. Product) aggregations but not raw label (e.g. `label:app`) aggregations.

**Comment by kc-creynold** [comment]
@Adam-Stack-PM @michaelmdresser CU is still seeing this issue post 1.97 upgrade.

**Comment by michaelmdresser** [comment]
@kc-creynold to clarify, are you talking about the reported issue with the Inspect (`/details`) page? Or the reported issue on the Allocation (`/allocations`) page? My read of the current situation is that we think `/allocation` is fixed but not `/details`.

**Comment by kc-creynold** [comment]
@michaelmdresser this would be /details page

@atyiadam please add any additional info that i may have missed.

**Comment by michaelmdresser** [comment]
@Adam-Stack-PM heads up for you here, not sure if this is being tracked as unfixed right now!

**Comment by atyiadam** [comment]
@michaelmdresser @kc-creynold Yes. `/allocations` page seems to be only displaying the correct resources. `/details` still has the issue of displaying non-related resources.

**Comment by wolfeaustin** [comment]
Thanks for reporting and working through this with us! There was a bug on the `/details` page that affected how filters were being mapped. This has been remedied and will be fixed in `1.98`.
