### ISSUE TITLE
OpenCost should support the AWS Fargate launch type which is billed differently than EC2

### ISSUE THREAD

**Issue by gillg** [opencost/opencost#1622]
**Is your feature request related to a problem? Please describe.**
The cost allocation for nodes launched in Fargate mode on AWS can't be correct.
OpenCost should support the "launch type" fargate as it supports the spot instances.
The fargate nodes are a little bit specials because each node can only host one pod, so there is no possible DaemonSet or other things like that.

**Describe the solution you'd like**
A Fargate instance is priced by cpu and memory allocated, there is no labels around that at node level, but there is automatic and forced "limits"
![image](https://user-images.githubusercontent.com/5639241/213892057-d3664808-2811-4cdb-ad5b-fab93582479a.png)
But the pod associated to the node (because is unique anyway) has a label `CapacityProvisioned` helping to compute the price
![image](https://user-images.githubusercontent.com/5639241/213894018-23cf1230-091b-43ef-946b-18b333829187.png)

So OpenCost should read them when `eks.amazonaws.com/compute-type=fargate` (instead of `eks.amazonaws.com/compute-type=ec2`) and compute a price. https://aws.amazon.com/fargate/pricing/
At some point EKS should also support FARGATE_SPOT, but it's not yet the case...

**Describe alternatives you've considered**
Nothing

**Additional context**
Exemple of labels added by EKS and the fargate profile at node level
![image](https://user-images.githubusercontent.com/5639241/213891570-2572d149-1035-478a-aead-beb350250791.png)
Labels at unique pode level
![image](https://user-images.githubusercontent.com/5639241/213894018-23cf1230-091b-43ef-946b-18b333829187.png)

**Comment by gillg** [comment]
Moreover, currently, using fargate cause some error logs `Invalid Pricing Key "us-east-1,,linux"` because `node.kubernetes.io/instance-type` is missing

**Comment by AjayTripathy** [comment]
Hi @gillg I think this makes a lot of sense and we can just parse the node / pod labels to come up with a price. Tentatively suggesting for v1.101

**Comment by gillg** [comment]
Great ! That will probably help many people :)
I took some time to understand the errors in logs !

**Comment by Pokom** [comment]
@AjayTripathy I had recently worked in this part o the codebase and would be more then happy to take on working on it. Feel free to assign me and I can start picking it up once I've got some time :smile:

**Comment by AjayTripathy** [comment]
Hey @Pokom that would be awesome!  I'm going to tag this as v1.101 tentatively-- do you think you can get this in before our v1.101 release March 7th? If not just let me know and we'll figure it out!

**Comment by disfluxly** [comment]
👍 to this. We use EKS Fargate _very_ heavily.

When building this functionality out, I would leave some flexibility for future `arm64` support (https://github.com/aws/containers-roadmap/issues/1629)

**Comment by Pokom** [comment]
Hey @AjayTripathy super sorry for the delayed response here, I won't be able to commit to getting this out for March 7th. I'm going to unassign myself until I can pick it up so someone else can pick up it up. If no one else picks it up before I can, I'll make every effort get it reviewed by the 7th

**Comment by AjayTripathy** [comment]
No worries @Pokom -- we'll let you know by unassigning if we have to pick it up on our end!

**Comment by gillg** [comment]
Little ping :)
Any chance having it in the next release or still too short for now ?

**Comment by AjayTripathy** [comment]
Hey @gillg this didn't make 101. Let me see about getting it prioritized for 102.

**Comment by coleEthomas** [comment]
We are also facing this same issue. would love a fix pushed out!

**Comment by caruccio** [comment]
Hello there. Any chances for this feature to be releases sometime in the near future?

**Comment by AjayTripathy** [comment]
Fargate is supported-- you can learn more about the state of Fargate support here: https://docs.google.com/document/d/1VHWXJ3rOMMRSpg--TkAHTinjZbL8O4P3u3ukuIxWQnk/edit#heading=h.ih07sliv9uw4

**Comment by mattray** [comment]
@AjayTripathy after reading through that I'm still not sure what the state of Fargate is for OpenCost vs. Kubecost given there's no reconciliation in OpenCost and the doc lists proposals for Asset data which wasn't in OpenCost at the time. The Kubecost docs have no references to Fargate in them, so I'm not sure where to start with sorting out what's supported in OpenCost.

**Comment by AjayTripathy** [comment]
Hey @mattray we basically should have good pricing estimates for Fargate today but not penny accuracy as we do for other EKS setups.

**Comment by mattray** [comment]
@AjayTripathy I don't think penny accuracy matters for OpenCost since there's no reconciliation, but if Fargate EKS nodes gets counted I think the issue can be closed

**Comment by StanislavRud** [comment]
The same problem. I use fargate nodes for karpenter and see in the logs:
`INF Error getting node pricing. Error: Invalid Pricing Key "us-east-1,,linux"`

version app 1.113.0

**Comment by motoki317** [comment]
What I've investigated so far:
Fargate pricing entries don't exist in `AmazonEC2` pricing list currently fetched by OpenCost.
e.g. https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ap-northeast-1/index.json

Fargate pricing do exist in AmazonECS pricing list, so perhaps we could utilize this list.
e.g. https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonECS/current/ap-northeast-1/index.json

**Comment by motoki317** [comment]
I've opened a PR for better support of Fargate nodes pricing calculation at #3350.
I've also published snapshot docker images at [ghcr.io/motoki317/opencost](https://github.com/motoki317/opencost/pkgs/container/opencost), so if anyone is interested in trying this out, you can use this pre-built image. (Use it at your own risk though)
It's already working great in my cluster, with correct prometheus metrics numbers. 😺 

You can use `ghcr.io/motoki317/opencost:patch-eks-fargate` to try #3350, or `:patch-eks` tag to try both #3350 and #3348.
If you're using the official OpenCost helm chart, set the following to values.yaml to override the image:

```yaml
opencost:
  exporter:
    image:
      repository: motoki317/opencost
      tag: patch-eks-fargate # or "patch-eks"
      pullPolicy: Always
```

**Comment by quirin-pauli** [comment]
@motoki317 I just tested your changes and now I finally get correct pricing for Fargate. Thank you so much!

Any chance we could get that merged in an upcoming release?
